### ISSUE TITLE
Unable to get BLID and password on i7

### ISSUE THREAD

**Issue by robert1030** [karlvr/homebridge-roomba2#95] opened 2021-12-16 01:49 UTC
### Expected Behavior
Get i7 robotpassword, blid, model name ... etc

### Current Behavior
Robot Data:
undefined
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
### Steps to Reproduce (for bugs)
1. cd /usr/local/lib/node_modules/
2. Manual install "sudo npm i -g homebridge-roomba2"
3. cd $(npm root -g)/homebridge-roomba2
4. sudo npm run getrobotpwd robot-ip

### Versions

- **Homebridge**: 1.3.8
- **Node**:     v16.13.1
- **Plugin**:   1.2.2

**Comment by karlvr** [comment] 2022-03-13 01:32
@robert1030 I think is a duplicate of several other issues. Please see #81 and #91.

**Closed by karlvr** 2022-03-13 01:32 UTC
Labels: support
