### ISSUE TITLE
Contact sensors not working

### ISSUE THREAD

**Issue by SebSemmi** [karlvr/homebridge-roomba2#5] opened 2020-10-29 20:34 UTC
the _running_ and _docked_ contact sensors don't work. are there some configurations necessary? Running Roomba 960, coming from homebridge-roomba-stv plugin.

**Comment by iRayanKhan** [comment] 2020-10-29 22:38
You may have to enable sensor notifications in the home app.

**Comment by iRayanKhan** [comment] 2020-10-31 02:42
Hey @SebSemmi,

I wanted to see if it worked for you?

To clarify, in the home app, click the house icon in the top left, scroll down 'till you see ```Home Settings```, Click Sensors, and enable the sensor you want. I will close this issue next week if there is no reply.

**Comment by SebSemmi** [comment] 2020-11-01 11:02
> You may have to enable sensor notifications in the home app.

I already had sensor notifications enabled. The problem was, the contacts did not open and close respectively. I enabled _Enable Keep Alive_ and _Auto Refresh Enabled_, now the sensors work. But I remember there where some downsides to this options and why there weren't enabled by default in the other plugins.

**Comment by iRayanKhan** [comment] 2020-11-02 04:20
Interesting. I haven't had any issue with those settings for a year. It does my whole down stairs just fine.

**Comment by dxdr** [comment] 2020-11-02 19:01
I am also having an issue with the contact sensors... specifically, the "docked" sensor operates in the opposite way as might be expected.  The Docked sensor shows closed when the roomba is docked, and opened when the roomba is not docked.  It seems the "Docked" Sensor should indicate if its docked, not that it is NOT docked

**Comment by iRayanKhan** [comment] 2020-11-02 19:31
I could add a setting to change the behavior of how you want the sensor to behave. I have add a setting called "Reverse Dock Sensor" for your interpretation. This will be added tonight in the next release.

**Comment by nikdata** [comment] 2020-11-02 21:00
I'll echo what @SebSemmi did to get their Roomba to work. Without enabling "Enable Keep Alive" and "Auto Refresh Enabled", I could toggle the switches on my Home App or on Homebridge and nothing would happen. If I used the iRobot app to activate the Roomba (or pushed the START button on the Roomba itself), the switches would show the correct value (open for Roomba running), but they wouldn't 'do much' other than show status.

Once I made the changes that @SebSemmi did, I'm now able to control my Roomba with the switches on my Home app.

Note, I did make sure to try with all notifications enabled but that didn't do anything either.

**Comment by SebSemmi** [comment] 2020-11-03 10:08
@nikdata you have to clarify, the Roomba should show in HomeKit as **one** switch and up to **three** sensors. You then could go into each sensor and set up an notification.

**Comment by nikdata** [comment] 2020-11-03 14:35
@SebSemmi Sorry for the poor wording on my previous post. You are correct that I have 1 switch (that has the ability to toggle on/off) and 3 sensors (one showing if bin is full, one showing whether the Roomba is running, and one showing if the Roomba is docked).

Earlier, I wanted to say that before I enabled "Enable Keep Alive" and "Auto Refresh", the toggle switch didn't do anything. If I went and turned the Roomba on myself, then the switch would show "toggle on". In other words, if I went to the switch in the Home app and toggled on, nothing would happen. However, once I enabled the options (Enable Keep Alive & Auto Refresh), then the switch on the Home app worked. In other words, I could now go and toggle the switch on through the Home app and the Roomba would turn on.

I hope that is clearer.

**Comment by iRayanKhan** [comment] 2020-11-03 15:59
SO @SebSemmi, do you notice any issues with keepAlive on, or refresh?

**Comment by whreams** [comment] 2020-12-10 16:36
Occasionally seeing the docked state not refreshed.  Unsure what the culprit is but my unit is only a few months old (s9) and my contacts are in great shape.  I also PM my unit monthly with wipes and an air compressor.  Don't believe the issue is mechanical...  Anyone else seeing the docked state not refreshed in HK?

**Comment by EagleMan2506** [comment] 2021-04-12 08:37
Hi every one, just got my Roomba 900 Series/Roomba 976.
try the plugin.
it does Activate the Roomba and it does stop it and sent it to the dock station.
but like in the issue:
https://github.com/homebridge-plugins/homebridge-roomba2/issues/39
there is a problem with updating the status (Charging/ not Charging) and the battery (always 100%)
i tried the sensors too (none worked)

i will try what @SebSemmi suggest and be back with results

thank you

**Comment by EagleMan2506** [comment] 2021-04-12 18:43
Check and after adding "Enable Keep Alive" and "Auto Refresh Enabled", now the sensors work for me too

but in this plugin:
https://www.npmjs.com/package/homebridge-roomba-stv

they sais:
"KEEP ALIVE (keepAlive set to true) - we will keep a connection to roomba, this will cause app to fail to connect to roomba in local network mode (cloud mode will work just fine, even in your home wifi). This will lead to better performance (status will refresh faster, and toggle will work faster as well). Keep in mind this will increase the Roomba battery consumption."

so its not OK to do so?

**Comment by khad** [comment] 2021-09-25 18:56
@karlvr My understanding is that the old options "Enable Keep Alive" and "Auto Refresh Enabled" are not being used in the latest betas. Should this issue be closed?

**Comment by karlvr** [comment] 2021-09-25 19:35
@khad thank you very much for helping triage and clean up the issues. Yes, those strategies have been removed. I'll close this. Hopefully the issue itself is still resolved… I'm pretty sure it is.

**Closed by karlvr** 2021-09-25 19:35 UTC
Labels: bug
